plugins: audible copyartifacts edit embedart fromfilename inline scrub # web?

# directory: ~/Books/Audiobooks
directory: /audiobooks

item_fields:
  first_artist: albumartist.split(', ',1)[0:1][0]
  padded_track: f"{track:02}"
  padded_series_position: series_position.zfill(2)

paths:
  # For books that belong to a series
  "albumtype:audiobook series_name::.+ series_position::.+": $first_artist/%ifdef{series_name}/%ifdef{padded_series_position} - $title
  "albumtype:audiobook series_name::.+": $first_artist/%ifdef{series_name}/$title
  # Stand-alone books
  "albumtype:audiobook": $first_artist/$album%aunique{}/$padded_track - $title
  default: $first_artist/$album%aunique{}/$padded_track - $title
  singleton: Non-Album/$artist - $title
  comp: Compilations/$album%aunique{}/$padded_track - $title
  albumtype_soundtrack: Soundtracks/$album/$track $title

# disables musicbrainz lookup, as it doesn't help for audiobooks
musicbrainz:
  enabled: false

embedart:
  auto: false
  remove_art_file: true

audible:
  # if the number of files in the book is the same as the number of chapters from Audible,
  # attempt to match each file to an audible chapter
  match_chapters: true
  source_weight: 0.0 # disable the source_weight penalty
  fetch_art: true # whether to retrieve cover art
  include_narrator_in_artists: false # include author and narrator in artist tag. Or just author
  keep_series_reference_in_title: true # set to false to remove ", Book X" from end of titles
  keep_series_reference_in_subtitle: true # set to false to remove subtitle if it contains the series name and the word book ex. "Book 1 in Great Series", "Great Series, Book 1"
  write_description_file: false # output desc.txt
  write_reader_file: false # output reader.txt
  region: us # the region from which to obtain metadata can be omitted, by default it is "us"
  # pick one of the available values: au, ca, de, es, fr, in, it, jp, us, uk
  # the region value can be set for each book individually during import/re-import
  # also it is automatically derived from 'WOAF' (WWWAUDIOFILE) tag
  # which may contain a URL such as 'https://www.audible.com/pd/ASINSTRING' or 'audible.com'

copyartifacts:
  extensions: .yml # so that metadata.yml is copied, see below

scrub:
  auto: true # optional, enabling this is personal preference
